import { HealthCenter } from "@/types/health-center.types";

// Datos simulados de centros de salud y fundaciones
export const healthCentersData: HealthCenter[] = [
  {
    id: 1,
    name: "Hospital Oncológico Nacional",
    type: "hospital",
    address: "Av. Principal 123",
    city: "Ciudad de México",
    country: "México",
    coordinates: [19.432608, -99.133209],
    phone: "+52 55 1234 5678",
    website: "www.hospitaloncologico.mx",
    schedule: "Lunes a Domingo, 24 horas",
    services: [
      "Oncología médica",
      "Radioterapia",
      "Quimioterapia",
      "Cirugía oncológica",
    ],
  },
  {
    id: 2,
    name: "Fundación Apoyo Contra el Cáncer",
    type: "foundation",
    address: "Calle Solidaridad 456",
    city: "Bogotá",
    country: "Colombia",
    coordinates: [4.710989, -74.072092],
    phone: "+57 1 987 6543",
    website: "www.fundacionapoyo.co",
    schedule: "Lunes a Viernes, 9:00 - 18:00",
    services: [
      "Apoyo psicológico",
      "Donaciones",
      "Grupos de apoyo",
      "Información",
    ],
  },
  {
    id: 3,
    name: "Clínica Especializada en Cáncer",
    type: "clinic",
    address: "Av. Salud 789",
    city: "Buenos Aires",
    country: "Argentina",
    coordinates: [-34.603684, -58.381559],
    phone: "+54 11 5555 4444",
    website: "www.clinicacancer.ar",
    schedule: "Lunes a Sábado, 8:00 - 20:00",
    services: ["Consultas", "Diagnóstico", "Tratamientos ambulatorios"],
  },
  {
    id: 4,
    name: "Centro de Apoyo para Pacientes",
    type: "support",
    address: "Calle Esperanza 321",
    city: "Santiago",
    country: "Chile",
    coordinates: [-33.447487, -70.673676],
    phone: "+56 2 3333 2222",
    website: "www.centroapoyo.cl",
    schedule: "Lunes a Viernes, 10:00 - 19:00",
    services: ["Asesoría legal", "Apoyo emocional", "Talleres", "Biblioteca"],
  },
  {
    id: 5,
    name: "Hospital General Universitario",
    type: "hospital",
    address: "Av. Universidad 555",
    city: "Lima",
    country: "Perú",
    coordinates: [-12.046374, -77.042793],
    phone: "+51 1 7777 8888",
    website: "www.hospitaluniversitario.pe",
    schedule: "Lunes a Domingo, 24 horas",
    services: ["Oncología", "Hematología", "Cuidados paliativos"],
  },
  {
    id: 6,
    name: "Fundación Luz y Esperanza",
    type: "foundation",
    address: "Calle Amanecer 111",
    city: "Quito",
    country: "Ecuador",
    coordinates: [-0.180653, -78.467838],
    phone: "+593 2 1111 2222",
    website: "www.luzyesperanza.ec",
    schedule: "Lunes a Viernes, 8:30 - 17:30",
    services: ["Donaciones", "Voluntariado", "Campañas de prevención"],
  },
  {
    id: 7,
    name: "Clínica Oncológica del Sur",
    type: "clinic",
    address: "Av. Sur 222",
    city: "Montevideo",
    country: "Uruguay",
    coordinates: [-34.901113, -56.164531],
    phone: "+598 2 9999 8888",
    website: "www.clinicaoncologica.uy",
    schedule: "Lunes a Viernes, 8:00 - 19:00, Sábados 9:00 - 13:00",
    services: ["Consultas", "Tratamientos", "Seguimiento"],
  },
  {
    id: 8,
    name: "Centro Integral de Apoyo",
    type: "support",
    address: "Calle Bienestar 333",
    city: "Caracas",
    country: "Venezuela",
    coordinates: [10.491016, -66.902061],
    phone: "+58 212 4444 3333",
    website: "www.centroapoyo.ve",
    schedule: "Lunes a Viernes, 9:00 - 17:00",
    services: ["Apoyo psicológico", "Nutrición", "Fisioterapia"],
  },
];
